#!/bin/sh

id=$1

if [ -z "$id" ]; then
    id=3djfzy
else
    # if $1 is a URL (https://www.shadertoy.com/view/tsBfDw) extract id from it
    if echo "$id" | grep / > /dev/null; then
        id=`echo "$id" | awk -F/ '{ print $NF }'`
    fi
fi

if ! echo "$id" | grep -E '^[a-zA-Z0-9]+$' > /dev/null; then
   echo "Usage: `basename "$0"` id" 1>&2
   exit 1
fi

user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'
referer="https://www.shadertoy.com/view/$id"
url='https://www.shadertoy.com/shadertoy'

# return 1 on empty input
validate() {
    awk 'BEGIN { r=1 } { print $0; r=0 }
         END { if (r) print "Invalid id?" | "cat 1>&2"; exit r }'
}

curl -s -A "$user_agent" -e "$referer" -d 's={"shaders":["'"$id"'"]}' "$url" | \
    json -a 'renderpass["0"]["code"]' | validate
